name: enmkit_fresh_start
description: "A new Flutter project for EnMKIT control."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Gardez une version de SDK compatible avec vos packages

dependencies:
  flutter:
    sdk: flutter

  # Base de données locale
  sqflite: ^2.3.2 
  path: ^1.9.0    

  # Gestion d'état
  provider: ^6.1.2 # Peut être mis à jour vers ^6.1.1 ou la dernière

  # Pour l'envoi et la réception de SMS
  sms_advanced: ^1.1.0 # MIS À JOUR vers une version plus récente et stable

  # Pour la gestion des permissions
  permission_handler: ^11.3.1 

  # Formatage des dates, nombres, etc.
  intl: ^0.19.0 

  # Graphiques
  fl_chart: ^0.64.0 # MIS À JOUR

  # Sauvegarde de petites préférences
  shared_preferences: ^2.2.3 # MIS À JOUR vers une version stable commune

  cupertino_icons: ^1.0.8 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.14.4 # Version commune et stable

  flutter_lints: ^3.0.2 # Peut être mis à jour si souhaité

# Configuration pour flutter_launcher_icons
# Assurez-vous que l'image existe bien à ce chemin RELATIF à la racine du projet
flutter_icons:
  android: true
  ios: true # Recommandé de générer pour les deux plateformes
  image_path: "C:/Users/JOEL/Downloads/enmkit-master/assets/images/icon/logo.png"

  # Si votre image est dans assets/images/icon/ic_launcher.png, utilisez ce chemin.

flutter:
  uses-material-design: true

  assets:
    # Ajoutez ici les dossiers contenant vos assets (images, etc.)
    # Exemple si vous avez des images pour les slides dans assets/images/
    - assets/images/
    # Assurez-vous que le dossier de votre icône d'application est listé ou son parent
    #- assets/icon/ # Si votre icône est dans assets/icon/
    # Ou si elle est dans assets/images/icon/ alors assets/images/ suffit si vous avez assets/images/ plus haut